#!/usr/bin/env node

"use strict";

var path = require("path");
var CLI = require(path.join("..","src","cli.js"));
var packageJSON = require("../package.json");

CLI(packageJSON.version).catch(console.error);
