"use strict";

require("1.js");
var v2 = require("2.js");
var v3 = require("3.js").v3;
var v4 = require("4.js").v;
var v5 = require("5.js")["v"];
v6 = require("6.js");
v7 = require("7.js").v7;
v8 = require("8.js").v;
v9 = require("9.js")["v"];
var { v10 } = require("10.js");
var { v: v11 } = require("11.js");
var { "v": v12 } = require("12.js");
({ v13 } = require("13.js"));
({ v: v14 } = require("14.js"));
({ "v": v15 } = require("15.js"));

module.exports = 1;
module.exports = t2;
module.exports = t[3];
module.exports.t4 = 4;
module.exports.t5 = "t5";
module.exports.t6 = true;
module.exports.t7 = t7;
module.exports.t8 = v;
module.exports.t9 = null;
module.exports.t10 = undefined;
module.exports.t11 = t11();
exports = 12;
exports = t13;
exports = t[14];
exports.t15 = 15;
exports.t16 = "t16";
exports.t17 = true;
exports.t18 = t18;
exports.t19 = v;
exports.t20 = null;
exports.t21 = undefined;
exports.t22 = t22();
